'use strict';

/**
 * Emits the SQL that puts a freshly migrated QA database into the exact state
 * the committed X_ITE 15.1.12 baseline was captured from.
 *
 * Why this exists: both baselines key every record on `<source>:<row id>`, and
 * those ids come from auto-increment counters. A rebuilt database hands out
 * different ones, so a comparison against the committed baselines reports all
 * sixty rows as missing and proves nothing. The counters are the only thing in
 * the way, and they can simply be set.
 *
 * What it creates, and nothing else:
 *
 * - the two QA accounts (`testqa` logs in, `XiteQA` owns the home place);
 * - a home place at the baseline's id, with a claimed block lot;
 * - the four catalogue objects the baseline's five pre-existing placements
 *   point at, at ids 1-4;
 * - those five pre-existing placements, at the baseline's ids and with the
 *   baseline's exact position and rotation bytes;
 * - the auto-increment values that make `run-seed.sh` land the 55 fixture rows
 *   on the baseline's ids.
 *
 * The pre-existing five are QA artefacts of the original capture session - a
 * dropped object, three plaza rows left at NULL placement, and one mall row.
 * They are reproduced from what the baseline records, byte for byte. No
 * historical citizen content is invented, and no asset file is fabricated: the
 * object directories those rows name are upload-area paths that the repository
 * has never carried (`spa/assets/object/` is gitignored). A missing Inline does
 * not affect placement - the `SharedObject` PROTO instance carries the
 * transform whether or not its geometry resolves - so the rows still measure
 * exactly what the contract is about.
 *
 * Run this BEFORE `run-seed.sh seed`, against a disposable database only.
 *
 * Usage:
 *   node tools/prepare-task-db.js | docker exec -i <db> sh -c 'mysql ...'
 */

const path = require('path');
const fs = require('fs');

const BASELINE = process.argv[2]
  || path.join(__dirname, '..', 'baselines', 'stored-15.1.12.json');
const baseline = JSON.parse(fs.readFileSync(BASELINE, 'utf8'));

/* bcrypt hash of 'testqa'. A QA password, never a deployment credential. */
const HASH = process.env.CTR_QA_PASS_HASH
  || '$2b$10$TGmMv.fWIwvNPpfWDtRfmODdSkqjZQqgMu11vTMfNERBzkU8wswEq';

/** The rows the fixture seed does not create: everything not named `QAFIX `. */
function preExisting() {
  const fixtureIds = new Set();
  baseline.records.forEach(record => {
    if (/\/qafix\//.test(record.stored.url)) {
      fixtureIds.add(`${record.source}:${record.id}`);
    }
  });
  return baseline.records.filter(r => !fixtureIds.has(`${r.source}:${r.id}`));
}

const rows = preExisting();
const objects = new Map();
rows.forEach(record => {
  const url = record.stored.url.replace(/^\/assets\/object\//, '');
  const slash = url.lastIndexOf('/');
  objects.set(record.stored.objectId, {
    id: record.stored.objectId,
    directory: url.slice(0, slash),
    filename: url.slice(slash + 1),
  });
});

/** The id the fixture seed's first row of each table must land on. */
function nextId(source) {
  const ids = baseline.records
    .filter(r => r.source === source && /\/qafix\//.test(r.stored.url))
    .map(r => r.id);
  return Math.min.apply(null, ids);
}

const homePlaceId = (rows.find(r => r.stored.placeType === 'home') || {}).stored;
const HOME_PLACE = homePlaceId ? homePlaceId.placeId : null;
if (!HOME_PLACE) {
  throw new Error('baseline carries no home placement; cannot recreate the home place id');
}

function quote(value) {
  if (value === null || value === undefined) {
    return 'NULL';
  }
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "''")}'`;
}

const lines = [];
const emit = sql => lines.push(sql);

emit('-- Generated by tools/prepare-task-db.js. Disposable QA databases only.');

// QA accounts. `chatdefault = 1` is what puts a member in the 3D view;
// `is_3d` alone does not, so a Playwright gate would wait on a world the 2D
// branch was never going to load.
[['testqa', 'testqa@example.invalid'], ['XiteQA', 'xiteqa@example.invalid']].forEach(
  ([username, email]) => {
    emit(`INSERT INTO wallet (balance) SELECT 1000 FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM member WHERE username = ${quote(username)});`);
    emit(`INSERT INTO member (avatar_id, email, password, status, username, wallet_id,
    chatdefault, is_3d, approved_at, password_reset_expire, last_daily_login_credit,
    last_weekly_role_credit, last_activity)
  SELECT 1, ${quote(email)}, ${quote(HASH)}, 1, ${quote(username)}, LAST_INSERT_ID(),
    1, 1, NOW(), NOW(), NOW(), NOW(), NOW()
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM member WHERE username = ${quote(username)});`);
  });

// Home place, at the baseline's id. The lot claim in seed-fixtures.js links it
// to a block afterwards; without that link GET /api/home/:username answers 400.
emit(`ALTER TABLE place AUTO_INCREMENT = ${HOME_PLACE};`);
emit(`INSERT INTO place (name, slug, type, member_id, private, status, description)
  SELECT 'XiteQA', NULL, 'home', m.id, 0, 1, 'placement fixture home'
    FROM member m WHERE m.username = 'XiteQA'
     AND NOT EXISTS (SELECT 1 FROM place WHERE type = 'home' AND member_id = m.id);`);
emit(`INSERT INTO home (place_id, home_design_id)
  SELECT p.id, '000' FROM place p WHERE p.id = ${HOME_PLACE}
   AND NOT EXISTS (SELECT 1 FROM home h WHERE h.place_id = p.id);`);
emit(`UPDATE member m JOIN place p ON p.id = ${HOME_PLACE}
   SET m.place_id = p.id WHERE m.username = 'XiteQA';`);

// Catalogue rows for the pre-existing placements, then the counter that makes
// the fixture seed's own objects land on the baseline's object ids.
Array.from(objects.values()).sort((a, b) => a.id - b.id).forEach(object => {
  emit(`INSERT INTO object (name, filename, directory, member_id, quantity, status, price)
  SELECT ${quote(`QA baseline object ${object.id}`)}, ${quote(object.filename)},
    ${quote(object.directory)}, 1, 999, 1, 0
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM object WHERE id = ${object.id});`);
});
emit(`ALTER TABLE object AUTO_INCREMENT = ${
  Math.min.apply(null, baseline.records
    .filter(r => /\/qafix\//.test(r.stored.url))
    .map(r => r.stored.objectId))};`);

// The five pre-existing placements, at their baseline ids and raw bytes.
rows.filter(r => r.source === 'object_instance').sort((a, b) => a.id - b.id).forEach(record => {
  emit(`INSERT INTO object_instance
  (id, object_id, object_name, member_id, place_id, position, rotation)
  SELECT ${record.id}, ${record.stored.objectId},
    ${quote(`QA baseline object ${record.stored.objectId}`)},
    ${record.stored.memberId}, ${record.stored.placeId},
    ${quote(record.stored.rawPosition)}, ${quote(record.stored.rawRotation)}
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM object_instance WHERE id = ${record.id});`);
});
emit(`ALTER TABLE object_instance AUTO_INCREMENT = ${nextId('object_instance')};`);

rows.filter(r => r.source === 'mall_object').sort((a, b) => a.id - b.id).forEach(record => {
  emit(`INSERT INTO mall_object (id, object_id, place_id, position, rotation)
  SELECT ${record.id}, ${record.stored.objectId}, ${record.stored.placeId},
    ${quote(record.stored.rawPosition)}, ${quote(record.stored.rawRotation)}
  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM mall_object WHERE id = ${record.id});`);
});
emit(`ALTER TABLE mall_object AUTO_INCREMENT = ${nextId('mall_object')};`);

console.log(lines.join('\n'));
